SECRET_KEY: "${TAK_SECRET_KEY}"
SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://ots:${TAK_POSTGRES_PASSWORD}@postgres:5432/ots"
OTS_RABBITMQ_SERVER_ADDRESS: "rabbitmq"
OTS_RABBITMQ_USERNAME: "tak_user"
OTS_RABBITMQ_PASSWORD: "${TAK_RABBITMQ_PASSWORD}"
OTS_MEDIAMTX_ENABLE: false
OTS_LOG_LEVEL: "INFO"
OTS_LISTENER_ADDRESS: "0.0.0.0"
OTS_LISTENER_PORT: 8089
OTS_TCP_STREAMING_PORT: 8088
OTS_SSL_STREAMING_PORT: 8443
SECURITY_PASSWORD_SALT: "${TAK_SECURITY_PASSWORD_SALT}"
